version: '3'

services:
  db-service:
    image: mysql:8.0
    deploy:
      replicas: 2
    ports:
      - 3306:3306
    environment:
           - MYSQL_ROOT_PASSWORD=Welcome123
           - MYSQL_DATABASE=musicstore
           - MYSQL_USER=root
           - MYSQL_PASSWORD=Welcome123
    volumes:
      - ./my-datavolume:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always


  backend-service:
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-service:3306/musicstore?createDatabaseIfNotExist=true&useSSL=true&requireSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Welcome123"
    image: prankurjain/music-backend
    deploy:
      replicas: 2
    ports: 
      - 8080:8080
    depends_on: 
      - 'db-service'
    restart: always

  frontend-service:
    image: prankurjain/music-frontend
    volumes: 
      - ./MusicStore:/usr/src/app
    ports: 
      - '4200:4200'
    links: 
      - 'backend-service'
    depends_on: 
      - 'backend-service'

volumes: 
  my-datavolume:
    