#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/musicstore?createDatabaseIfNotExist=true&useSSL=true&requireSSL=false
#    username: root  
#    password: Welcome123
#    
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update