


apiVersion: v1
kind: Service
metadata:
 name: localhost
 labels:
   app: localhost
   tier: database
spec:
  selector:
    app: localhost
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: localhost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: localhost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localhost
  template:
    metadata:
      labels:
        app: localhost
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-superpassword
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: dbname
        volumeMounts: 
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim


---
